name: 'Newline At EOF'
description: 'Ensures all files that have changed in a PR have exactly 1 newline at EOF'
author: 'Gopal Sharma <gps@surya-soft.com>'
inputs:
  GH_TOKEN:
    description: GitHub Token used to interact with GitHub API
    required: true
  IGNORE_FILE_PATTERNS:
    description: Paths to ignore 
    required: false
  COMMIT_MESSAGE:
    description: Specify commit message 
    required: false
runs:
  using: node12
  main: 'dist/index.js'
