name: Build package with ncc
on: [pull_request]

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build node js module
        uses: gps/ncc-gha@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
